### ISSUE TITLE
Shared-cache in-memory sqlite is not supported?

### ISSUE THREAD

**Issue by peter-wangxu** [ghaering/pysqlite#118]
I am using sqlite3 to implement a queue in memory, when i tried to initialize a shared-cache sqlite3 connection, error occurred.

here is the traceback:
Python version: 3.5.3 on Windows 10(x64)

```python
Error
Traceback (most recent call last):
  File "C:\Python35\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python35\lib\unittest\case.py", line 601, in run
    testMethod()
  File "C:\Users\user\PycharmProjects\persist-queue\tests\test_sqlqueue.py", line 116, in test_multi_threaded_multi_producer
    auto_commit=self.auto_commit)
  File "C:\Users\user\PycharmProjects\persist-queue\persistqueue\sqlbase.py", line 75, in __init__
    self._init()
  File "C:\Users\user\PycharmProjects\persist-queue\persistqueue\sqlqueue.py", line 40, in _init
    super(SQLiteQueue, self)._init()
  File "C:\Users\user\PycharmProjects\persist-queue\persistqueue\sqlbase.py", line 102, in _init
    self.timeout)
  File "C:\Users\user\PycharmProjects\persist-queue\persistqueue\sqlbase.py", line 111, in _new_db_connection
    check_same_thread=not multithreading)
sqlite3.OperationalError: unable to open database file
```

Code of `sqlbase.py`
```python
95         if self.multithreading:
96             if not self.memory_sql:
97                 self._putter = self._new_db_connection(
98                     self.path, self.multithreading, self.timeout)
99             else:
100                self._putter = self._new_db_connection(
101                    'file::memory:?cache=shared', self.multithreading,
102                    self.timeout)
```
any plan to support the path `file::memory:?cache=shared` described at link https://www.sqlite.org/inmemorydb.html

Thanks
Peter

**Comment by ghaering** [comment]
This relates to the version of the sqlite3 module in the Python standard library. pysqlite itself only works on Python 2.7. I am closing this then.

**Comment by berkerpeksag** [comment]
FTR, you need to pass `uri=True` to use the URI format in the stdlib sqlite3. Also, you may have an outdated SQLite version installed on your system.
