### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found. & SystemError: dynamic module not initialized properly

### ISSUE THREAD

**Issue by cloud-admin** [ghaering/pysqlite#125]
Hi there:

    I've install the pysqlite on my Windows PC using `pip install pysqlite`.

```
C:\Users\Admin>pip install pysqlite
Collecting pysqlite
Installing collected packages: pysqlite
Successfully installed pysqlite-2.8.3
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
```

But when i try to import pysqlite, it failed.

```python

>>> from pysqlite2 import dbapi2 as sqlite3
import pysqlite2 # directory C:\Python27\lib\site-packages\pysqlite2
# C:\Python27\lib\site-packages\pysqlite2\__init__.pyc matches C:\Python27\lib\s
ite-packages\pysqlite2\__init__.py
import pysqlite2 # precompiled from C:\Python27\lib\site-packages\pysqlite2\__in
it__.pyc
# C:\Python27\lib\site-packages\pysqlite2\dbapi2.pyc matches C:\Python27\lib\sit
e-packages\pysqlite2\dbapi2.py
import pysqlite2.dbapi2 # precompiled from C:\Python27\lib\site-packages\pysqlit
e2\dbapi2.pyc
# C:\Python27\lib\collections.pyc matches C:\Python27\lib\collections.py
import collections # precompiled from C:\Python27\lib\collections.pyc
import _collections # builtin
# C:\Python27\lib\keyword.pyc matches C:\Python27\lib\keyword.py
import keyword # precompiled from C:\Python27\lib\keyword.pyc
# C:\Python27\lib\heapq.pyc matches C:\Python27\lib\heapq.py
import heapq # precompiled from C:\Python27\lib\heapq.pyc
import itertools # builtin
import _heapq # builtin
import thread # builtin
import datetime # builtin
import time # builtin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pysqlite2\dbapi2.py", line 28, in <module>

    from pysqlite2._sqlite import *
ImportError: DLL load failed: The specified module could not be found.
```

I copied the _sqlite.pyd file into .\DLLS, and found this:

```python
>>> from _sqlite3 import *
import _sqlite3 # dynamically loaded from C:\Python27\DLLs\_sqlite3.pyd
>>> from _sqlite import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: dynamic module not initialized properly
```

I tried to find the reason of ***dynamic module not initialized properly*** using google, but no useful info. So , is there anyone meet this problem ? and how you fix this ? Thanks.

**Comment by pouyamiralayi** [comment]
hello there! i have the same error output using the pysqlcipher3 as my wrapper.
i dependency walked the _sqlite3.pyd (for my case would be: _sqlite3.cp36-win32.pyd) and it seems missing libeay32.dll and msvcr90.DLL, so i put these libraries in system32 directory but the problem is not solved.
thanks in advance.

**Comment by ghaering** [comment]
I cannot support Windows builds here. Closing due to inactivity.
