### ISSUE TITLE
Missing parentheses in call to 'print' when installing on Python 3.4 on Windows 32-bit

### ISSUE THREAD

**Issue by ghost** [ghaering/pysqlite#71]
* Windows 8.1 8.1 x86, Python 3.4
* When I try to install pysqlite I get the following error and a hit that Sphinx may be missing, although that's not true

```
C:\Python34>pip3 install pysqlite
Downloading/unpacking pysqlite
  Downloading pysqlite-2.6.3.tar.gz (76kB): 76kB downloaded
  Running setup.py egg_info for package pysqlite
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pysqlite\setup.py",
line 85
        print "Is sphinx installed? If not, try 'sudo easy_install sphinx'."
                                                                           ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pysqlite\setup.py", line
 85

    print "Is sphinx installed? If not, try 'sudo easy_install sphinx'."

                                                                       ^

SyntaxError: Missing parentheses in call to 'print'

----------------------------------------
Cleaning up...
```

However Sphinx v1.2.3 is installed:

```
appdirs (1.4.0)
Warning: cannot find svn location for apsw==3.8.5-r1
apsw (3.8.5-r1)
bip32utils (0.1)
bottle (0.12.8)
certifi (14.05.14)
CherryPy (3.6.0)
colorama (0.3.3)
colorlog (2.4.0)
counterparty-lib (9.49.4)
cov-core (1.15.0)
coverage (3.7.1)
Django (1.7.2)
docutils (0.12)
ecdsa (0.11)
Flask (0.10.1)
Flask-HTTPAuth (2.3.0)
itsdangerous (0.24)
Jinja2 (2.7.3)
json-rpc (1.7.0)
MarkupSafe (0.23)
pip (1.4.1)
prettytable (0.7.2)
progressbar33 (2.4)
py (1.4.26)
py2exe (0.9.2.2)
pycoin (0.52)
pycrypto (2.6.1)
Pygments (2.0.2)
pymongo (2.7.2)
pysha3 (0.3)
pytest (2.6.3)
pytest-cov (1.8.0)
python-bitcoinlib (0.3.0)
python-dateutil (2.2)
pywin32 (219)
requests (2.4.2)
serpent (1.8)
setuptools (2.1)
six (1.9.0)
Sphinx (1.2.3)
tendo (0.2.6)
tornado (4.0.2)
virtualenv (1.11.6)
Werkzeug (0.9.6)
```

In pip.log:

```

      File "<string>", line 16, in <module>

      File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pysqlite\setup.py", line 85

        print "Is sphinx installed? If not, try 'sudo easy_install sphinx'."

                                                                           ^

    SyntaxError: Missing parentheses in call to 'print'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pysqlite\setup.py", line 85

    print "Is sphinx installed? If not, try 'sudo easy_install sphinx'."

                                                                       ^

SyntaxError: Missing parentheses in call to 'print'

----------------------------------------

Cleaning up...

  Removing temporary dir C:\Users\rippler\AppData\Local\Temp\pip_build_rippler...
Command python setup.py egg_info failed with error code 1 in C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pysqlite

Exception information:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\basecommand.py", line 134, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\commands\install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\req.py", line 1134, in prepare_files
    req_to_install.run_egg_info()
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\req.py", line 259, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Python34\lib\site-packages\pip-1.4.1-py3.4.egg\pip\util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in C:\Users\rippler\AppData\Local\Temp\pip_build_rippler\pysqlite

```

I get the same error with `easy_install`.
```
    {'__file__':setup_script, '__name__':'__main__'}
  File "C:\Python34\lib\site-packages\setuptools\compat.py", line 78, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 85
    print "Is sphinx installed? If not, try 'sudo easy_install sphinx'."
                                                                       ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by cilia** [comment]
This is probably because `pysqlite` is not written for Python 3 yet.

**Comment by ghaering** [comment]
For Python 3.x, use the builting sqlite3 module. This *is* the Python 3 port of pysqlite.
